### ISSUE TITLE
A catchy package name

### ISSUE THREAD

**Issue by dspp779** [NTHU-NLPLAB/NLPLab_toolkit#1]
`NTHU_NLPLab_toolkit` is toooooo long🤣

How about a more catchy name like `call-api`?

**Comment by yizzycool** [comment]
How about ```large-pigs``` (Language Assistant that Revises Grammatical Errors and Provides Idiomatic Grammar Suggestion)

**Comment by sappy5678** [comment]
推推 解字 (jiezi)

**Comment by dspp779** [comment]
`leap` stands for Linguistic, Engineering, And Pedagogy by @jasonatnlplabdotcc

**Comment by sappy5678** [comment]
nlpLeap
